when:
    event: manual

steps:
  - name: build-push-api
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: containers.nsynk.de
      repo: containers.nsynk.de/freeframe/api
      tags:
        - latest
      dockerfile: apps/api/Dockerfile.prod
      # Root context — API copies from apps/api and packages/transcoder
      context: .
      username:
        from_secret: nsynk_container-registry_username
      password:
        from_secret: nsynk_container-registry_password

  - name: build-push-web
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: containers.nsynk.de
      repo: containers.nsynk.de/freeframe/web
      tags:
        - latest
      dockerfile: apps/web/Dockerfile.prod
      context: apps/web
      build_args:
        - NEXT_PUBLIC_API_URL=/api
      username:
        from_secret: nsynk_container-registry_username
      password:
        from_secret: nsynk_container-registry_password
